// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1e714b8e-427b-477a-aaea-c4985163067e"),
                            DateTime = new DateTime(2024, 2, 9, 13, 46, 52, 594, DateTimeKind.Local).AddTicks(6980),
                            IsActived = false,
                            LastName = "LastName 1",
                            Name = "User 1"
                        },
                        new
                        {
                            UserId = new Guid("18749e3c-7465-4360-bc60-624ed021013d"),
                            DateTime = new DateTime(2024, 2, 9, 13, 46, 52, 594, DateTimeKind.Local).AddTicks(6997),
                            IsActived = false,
                            LastName = "LastName 2",
                            Name = "User 2"
                        },
                        new
                        {
                            UserId = new Guid("8abd9ced-a210-4ebf-b241-6bb14e2178dc"),
                            DateTime = new DateTime(2024, 2, 9, 13, 46, 52, 594, DateTimeKind.Local).AddTicks(6999),
                            IsActived = false,
                            LastName = "LastName 3",
                            Name = "User 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
